{% set name = "pysmb" %}
{% set version = "1.2.5" %}
{% set sha256 = "7aedd5e003992c6c78b41a0da4bf165359a46ea25ab2a9a1594d13f471ad7287" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyasn1

test:
  imports:
    - smb
    - nmb
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/miketeo/pysmb
  license: Zlib
  license_file: LICENSE
  summary: pysmb is an experimental SMB/CIFS library written in Python to support file sharing between Windows and Linux machine
  doc_url: https://github.com/miketeo/pysmb
  dev_url: https://github.com/miketeo/pysmb

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
